name: reviewdog
on:
  pull_request:
    branches: [ main-nuxt ]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Run eslint with reviewdog
        uses: reviewdog/action-eslint@v1.0.0
        with:
          level: error
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
