name: reviewdog
on:
  pull_request:
    branches: [ main-nuxt ]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run eslint with reviewdog
        uses: reviewdog/action-eslint@v1.0.0
        with:
          level: error
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          eslint_flags: "--quiet --ignore-path .gitignore --ext .js,.ts,.vue ."
          args: "-filter-mode='nofilter' -fail-on-error='true'"
